#!/usr/bin/env python3
"""Build a compact podcast archive map for agents."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path

from extract_podcast_sources import candidate_topics, slugify
from podcast_source_data import (
    DEFAULT_PEOPLE_SOURCE,
    DEFAULT_PODCAST_SOURCE,
    ROOT,
    read_people,
    read_podcasts,
)


DEFAULT_OUTPUT = ROOT / "sources" / "podcast-archive-summary.md"
DEFAULT_AGENT_OUTPUT = ROOT / ".tmp" / "podcast-archive-summary.md"


def clean_text(value: object) -> str:
    return " ".join(str(value or "").split())


def person_label(slug: str, people: dict[str, dict[str, object]]) -> str:
    title = clean_text(people.get(slug, {}).get("title") or slug)
    return f"[{title}](/people/{slug}/)"


def episode_label(episode: dict[str, object]) -> str:
    return f"[{episode['title']}](/podcasts/{episode['slug']}/)"


def chapter_lines(episode: dict[str, object], max_chapters: int) -> list[str]:
    chapters = episode.get("chapters")
    if not isinstance(chapters, list) or not chapters:
        return ["  - No chapter clips in the source file; open the source episode if this looks relevant."]

    lines = []
    for chapter in chapters[:max_chapters]:
        if not isinstance(chapter, dict):
            continue
        title = clean_text(chapter.get("title"))
        if not title:
            continue
        time = clean_text(chapter.get("time"))
        url = clean_text(chapter.get("url"))
        prefix = f"{time} - " if time else ""
        if url:
            lines.append(f"  - {prefix}[{title}]({url})")
        else:
            lines.append(f"  - {prefix}{title}")

    remaining = len(chapters) - len(lines)
    if remaining > 0:
        lines.append(f"  - {remaining} more chapter clips in the source file.")
    return lines or ["  - No usable chapter titles in the source file."]


def build_summary(
    podcast_source: Path,
    people_source: Path,
    max_chapters: int,
    topic_limit: int,
) -> str:
    episodes = read_podcasts(podcast_source)
    people = read_people(people_source)
    appearances: dict[str, list[dict[str, object]]] = defaultdict(list)
    topic_counter: Counter[str] = Counter()
    topic_examples: dict[str, list[dict[str, object]]] = defaultdict(list)

    for episode in episodes:
        for guest in episode.get("guests", []):
            if isinstance(guest, str) and guest:
                appearances[guest].append(episode)
        for topic in candidate_topics(episode):
            topic_counter[topic] += 1
            if len(topic_examples[topic]) < 5:
                topic_examples[topic].append(episode)

    lines = [
        "# Podcast Archive Summary",
        "",
        "This file is generated by `python scripts/build_podcast_archive_summary.py`.",
        "Use it before opening full podcast source files.",
        "",
        "## Counts",
        "",
        f"- Episodes: {len(episodes)}",
        f"- People: {len(set(people) | set(appearances))}",
        f"- Topic candidates: {len(topic_counter)}",
        "",
        "## Episode Summaries",
        "",
    ]

    for episode in episodes:
        summary = clean_text(episode.get("intro") or episode.get("description"))
        guests = [
            person_label(guest, people)
            for guest in episode.get("guests", [])
            if isinstance(guest, str) and guest
        ]
        topics = [clean_text(topic) for topic in episode.get("topics", []) if clean_text(topic)]
        candidates = candidate_topics(episode)[:10]

        lines.extend(
            [
                f"### {episode['title']}",
                "",
                f"- Local page: /podcasts/{episode['slug']}/",
                f"- Original episode: {episode['source_url']}",
                f"- Source file: `{episode['source_episode']}`",
                f"- Guests: {', '.join(guests) if guests else 'No guest metadata in source.'}",
                f"- Source topics: {', '.join(topics) if topics else 'No source topics.'}",
                f"- Topic candidates: {', '.join(candidates) if candidates else 'No chapter-derived candidates.'}",
                f"- Short summary: {summary if summary else 'No intro or description in source metadata.'}",
                "- Chapter summary:",
            ]
        )
        lines.extend(chapter_lines(episode, max_chapters))
        lines.append("")

    lines.extend(["## People Index", ""])
    for slug in sorted(set(people) | set(appearances)):
        person = people.get(slug, {"title": slug})
        episode_refs = [f"/podcasts/{episode['slug']}/" for episode in appearances.get(slug, [])]
        refs = ", ".join(episode_refs[:8])
        if len(episode_refs) > 8:
            refs = f"{refs}, +{len(episode_refs) - 8} more"
        lines.append(f"- {person_label(slug, people)}: {refs if refs else 'No podcast appearances found.'}")

    lines.extend(["", "## Topic Candidates", ""])
    for topic, count in topic_counter.most_common(topic_limit):
        examples = ", ".join(f"/podcasts/{episode['slug']}/" for episode in topic_examples[topic])
        lines.append(f"- `{slugify(topic)}` ({count}): {topic}. Episodes: {examples}")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--podcast-source", type=Path, default=DEFAULT_PODCAST_SOURCE)
    parser.add_argument("--people-source", type=Path, default=DEFAULT_PEOPLE_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--agent-output", type=Path, default=DEFAULT_AGENT_OUTPUT)
    parser.add_argument("--max-chapters", type=int, default=14)
    parser.add_argument("--topic-limit", type=int, default=300)
    args = parser.parse_args()

    summary = build_summary(args.podcast_source, args.people_source, args.max_chapters, args.topic_limit)
    for output in (args.output, args.agent_output):
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(summary, encoding="utf-8")

    print(f"wrote {args.output}")
    print(f"wrote {args.agent_output}")


if __name__ == "__main__":
    main()
