#!/usr/bin/env python3
"""Check the graph explorer's landing and full-page contracts.

This is intentionally a dependency-free static regression check. The graph UI
is browser JavaScript, but its source-level contracts are important: the
landing must use generated graph data, node exploration must push the existing
history state, the responsive control CSS and reduced-motion branch must stay
intact, and the full explorer's canvas click behavior must not drift.
"""

from __future__ import annotations

import json
from html.parser import HTMLParser
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
NARROW_VIEWPORT_PX = 390
REDUCED_MOTION_QUERY = (
    'window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches'
)


class ElementParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.elements: list[dict[str, object]] = []
        self.stack: list[dict[str, object]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        frame: dict[str, object] = {
            "tag": tag,
            "attrs": dict(attrs),
            "text": "",
        }
        self.elements.append(frame)
        self.stack.append(frame)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.elements.append({"tag": tag, "attrs": dict(attrs), "text": ""})

    def handle_endtag(self, tag: str) -> None:
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index]["tag"] == tag:
                del self.stack[index:]
                return

    def handle_data(self, data: str) -> None:
        for frame in self.stack:
            frame["text"] = str(frame["text"]) + data


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def block(source: str, start: str, end: str) -> str:
    start_index = source.index(start)
    end_index = source.index(end, start_index)
    return source[start_index:end_index]


def balanced_block(source: str, start: str, message: str) -> str:
    start_index = source.find(start)
    require(start_index >= 0, message)
    open_index = source.find("{", start_index)
    require(open_index >= 0, message)

    depth = 0
    for index in range(open_index, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start_index : index + 1]
    raise AssertionError(message)


def check_landing_markup(source: str | None = None) -> None:
    source = source or (ROOT / "index.md").read_text(encoding="utf-8")
    parser = ElementParser()
    parser.feed(source)

    controls = [
        element
        for element in parser.elements
        if element["tag"] == "button"
        and "data-graph-random-control" in element["attrs"]
    ]
    roots = [
        element
        for element in parser.elements
        if element["tag"] == "section"
        and "data-graph-connections" in element["attrs"]
        and "data-graph-random" in element["attrs"]
    ]
    explorers = [
        element
        for element in parser.elements
        if element["tag"] == "div" and "data-graph-explorer" in element["attrs"]
    ]

    require(len(explorers) == 1, "landing must have one graph explorer wrapper")
    require(len(controls) == 1, "landing must have one Random node control")
    require(len(roots) == 1, "landing must have one random graph root")

    control = controls[0]
    root = roots[0]
    control_attrs = control["attrs"]
    root_attrs = root["attrs"]
    require(control_attrs.get("type") == "button", "Random node must be a button")
    require("Random node" in str(control["text"]), "Random node control must be visibly labeled")
    require(
        "graph-reroll" in str(control_attrs.get("class", "")).split(),
        "Random node must retain the graph-reroll styling hook",
    )
    require(control_attrs.get("aria-controls") == root_attrs.get("id"), "Random node must control the landing graph")
    require(source.index("data-graph-random-control") < source.index("data-graph-connections"), "Random node must be adjacent before the graph")
    require("data-node-id" not in source, "landing markup must not invent graph node data")


def check_graph_data() -> None:
    graph = json.loads((ROOT / "graph" / "graph.json").read_text(encoding="utf-8"))
    nodes = graph.get("nodes")
    links = graph.get("links")
    require(isinstance(nodes, list) and isinstance(links, list), "generated graph must contain node and link lists")
    require(graph.get("generated_at") == "generated-by-scripts/build_graph.py", "graph must remain generated by the graph pipeline")
    counts = graph.get("counts", {})
    require(counts.get("nodes") == len(nodes), "graph node count must match generated nodes")
    require(counts.get("links") == len(links), "graph link count must match generated links")

    node_ids = {node.get("id") for node in nodes if isinstance(node, dict)}
    require(None not in node_ids, "generated graph nodes must have stable ids")
    require({"wiki", "article", "podcast", "person", "book", "topic"}.issubset({node.get("type") for node in nodes}), "graph must retain the original node types")
    for link in links:
        require(link.get("source") in node_ids and link.get("target") in node_ids, "generated graph links must resolve to generated nodes")


def check_source_contracts(landing: str | None = None, full: str | None = None) -> None:
    landing = landing or (ROOT / "assets" / "page-graph.js").read_text(encoding="utf-8")
    full = full or (ROOT / "assets" / "graph.js").read_text(encoding="utf-8")

    require(landing.count('fetch(siteUrl("/graph/graph.json"))') == 1, "landing must load the generated graph")
    require(full.count('fetch(siteUrl("/graph/graph.json"))') == 1, "full explorer must load the generated graph")

    random_block = block(landing, "function pickRandomCenter", "function linkedNodes")
    require('typeKey(node) === "wiki"' in random_block, "landing random selection must retain its existing wiki eligibility")
    require("degreeById.get(node.id) || 0) >= 4" in random_block, "landing random selection must retain its existing degree threshold")
    require("const pool = rich.length ? rich : nodes;" in random_block, "landing random selection must retain its existing fallback")

    landing_links = block(landing, "function linkedNodes", "// Round-robin across types")
    require("for (const link of graph.links || [])" in landing_links, "landing related nodes must come from every generated graph link")
    require("return Array.from(linked.values())" in landing_links, "landing must retain every direct related node")
    require("const related = groupedRelatedHtml(linked);" in landing, "landing must render the full related-node information")
    require("all ${linked.length} connections" in landing, "landing must expose the full related-node count")

    require('const reroll = random ? () => showNode(pickRandomCenter(graph, degreeById), "push") : null;' in landing, "Random node must reuse the landing reroll selection and push history")
    require('onReroll: reroll' in landing, "generated and adjacent Random node controls must share reroll behavior")
    require('randomControl.addEventListener("click", reroll)' in landing, "adjacent Random node must be keyboard/click activatable")
    require('onExplore: (next) => showNode(next, "push")' in landing, "landing node exploration must continue to push widget history")
    show_node = block(landing, "const showNode = (node, historyMode) => {", "const reroll =")
    require(
        'if (historyMode === "push") pushWidgetHistory(key, node);' in show_node,
        "landing node exploration must preserve widget history",
    )

    landing_canvas = block(landing, 'canvas.addEventListener("click"', "let resizeTimer")
    require("if (!hit || hit.center) return;" in landing_canvas, "landing center-click behavior must remain unchanged")
    require("if (opts && opts.onExplore) opts.onExplore(hit.node);" in landing_canvas, "landing node clicks must use existing exploration semantics")

    full_canvas = block(full, 'canvas.addEventListener("click"', "// keyboard: Backspace/Esc")
    require("if (hit.center) window.location.href = nodeUrl(hit.node);" in full_canvas, "full explorer center click behavior must remain unchanged")
    require("else setFocus(hit.node, { push: true });" in full_canvas, "full explorer neighbor clicks must continue selection/history behavior")

    full_neighbors = block(full, "function neighborsOf", "const TYPE_ORDER")
    require("neighborById.get(node.id)" in full_neighbors, "full explorer must derive related nodes from generated graph adjacency")
    require("return Array.from(ids)" in full_neighbors, "full explorer must retain every direct related node")
    require("setFocus(next, { push: true });" in full, "full explorer related-node clicks must continue selection/history behavior")


def check_responsive_motion_contracts(css: str | None = None, landing: str | None = None) -> None:
    css = css or (ROOT / "assets" / "pagecss" / "content.css").read_text(encoding="utf-8")
    landing = landing or (ROOT / "assets" / "page-graph.js").read_text(encoding="utf-8")

    toolbar = balanced_block(
        css,
        ".home-graph-toolbar {",
        "landing graph toolbar CSS is missing",
    )
    require("display: flex;" in toolbar, "landing graph toolbar must remain a flex container")
    require("justify-content: flex-end;" in toolbar, "landing graph toolbar must retain desktop alignment")

    narrow_media = balanced_block(
        css,
        "@media (max-width: 600px)",
        "landing graph must retain its narrow viewport media query",
    )
    breakpoint = re.search(r"max-width:\s*(\d+)px", narrow_media)
    require(breakpoint is not None, "landing graph narrow media query must have a pixel breakpoint")
    require(
        NARROW_VIEWPORT_PX <= int(breakpoint.group(1)),
        "landing graph responsive contract must cover the 390px viewport",
    )

    narrow_toolbar = balanced_block(
        narrow_media,
        ".home-graph-toolbar {",
        "narrow landing graph toolbar CSS is missing",
    )
    require(
        "justify-content: stretch;" in narrow_toolbar,
        "landing graph toolbar must stretch at the narrow viewport",
    )
    narrow_control = balanced_block(
        narrow_media,
        ".home-graph-toolbar .graph-reroll {",
        "narrow Random node control CSS is missing",
    )
    require(
        "width: 100%;" in narrow_control,
        "landing Random node control must fill the toolbar at narrow width",
    )
    require(
        "margin-right: 0;" in narrow_control,
        "landing Random node control must not add horizontal margin at narrow width",
    )

    require(
        REDUCED_MOTION_QUERY in landing,
        "landing graph must detect prefers-reduced-motion",
    )
    animation = block(landing, "if (REDUCED) {", "\n  }\n\n  function render")
    reduced_branch = block(animation, "if (REDUCED) {", "    } else {")
    require(
        "anim = 1;" in reduced_branch and "draw();" in reduced_branch,
        "reduced-motion branch must finalize and draw immediately",
    )
    require(
        "requestAnimationFrame" not in reduced_branch,
        "reduced-motion branch must not request animation frames",
    )
    require(
        "requestAnimationFrame(step);" in animation,
        "normal-motion branch must retain its animation path",
    )


def expect_contract_failure(description: str, check, expected_message: str) -> None:
    try:
        check()
    except AssertionError as error:
        require(
            str(error) == expected_message,
            f"{description} mutation failed for an unexpected contract",
        )
    else:
        raise AssertionError(f"{description} mutation was accepted")


def check_responsive_motion_mutation_guards(css: str, landing: str) -> None:
    """Reject targeted responsive and reduced-motion contract mutations."""

    narrow_media = balanced_block(
        css,
        "@media (max-width: 600px)",
        "narrow landing graph CSS is missing for the mutation self-test",
    )
    narrow_control = balanced_block(
        narrow_media,
        ".home-graph-toolbar .graph-reroll {",
        "narrow Random node control CSS is missing for the mutation self-test",
    )
    original_width = "width: 100%;"
    mutated_width = "width: auto;"
    require(original_width in narrow_control, "responsive mutation self-test did not find the width contract")
    mutated_control = narrow_control.replace(original_width, mutated_width, 1)
    mutated_css = css.replace(narrow_control, mutated_control, 1)
    require(mutated_css != css, "responsive mutation self-test did not change the source")
    expect_contract_failure(
        "responsive width",
        lambda: check_responsive_motion_contracts(mutated_css, landing),
        "landing Random node control must fill the toolbar at narrow width",
    )

    original_query = REDUCED_MOTION_QUERY
    mutated_query = original_query.replace("reduce", "no-preference")
    mutated_landing = landing.replace(original_query, mutated_query, 1)
    require(mutated_landing != landing, "reduced-motion query mutation self-test did not change the source")
    expect_contract_failure(
        "reduced-motion query",
        lambda: check_responsive_motion_contracts(css, mutated_landing),
        "landing graph must detect prefers-reduced-motion",
    )

    animation = block(landing, "if (REDUCED) {", "\n  }\n\n  function render")
    reduced_branch = block(animation, "if (REDUCED) {", "    } else {")
    original_animation = "anim = 1;"
    mutated_animation = "anim = 0;"
    require(
        original_animation in reduced_branch,
        "reduced-motion animation mutation self-test did not find the finalization contract",
    )
    mutated_branch = reduced_branch.replace(original_animation, mutated_animation, 1)
    mutated_landing = landing.replace(reduced_branch, mutated_branch, 1)
    require(
        mutated_landing != landing,
        "reduced-motion animation mutation self-test did not change the source",
    )
    expect_contract_failure(
        "reduced-motion finalization",
        lambda: check_responsive_motion_contracts(css, mutated_landing),
        "reduced-motion branch must finalize and draw immediately",
    )


def check_history_mutation_guard(landing: str, full: str) -> None:
    """Ensure the history assertion rejects the reviewer's exact mutation."""

    original_call = 'if (historyMode === "push") pushWidgetHistory(key, node);'
    mutated_call = 'if (historyMode === "push") replaceWidgetHistory(key, node);'
    mutated_landing = landing.replace(original_call, mutated_call, 1)
    require(mutated_landing != landing, "history mutation self-test did not change the source")

    try:
        check_source_contracts(mutated_landing, full)
    except AssertionError as error:
        require(
            str(error) == "landing node exploration must preserve widget history",
            "history mutation self-test failed for an unexpected contract",
        )
    else:
        raise AssertionError(
            "history mutation self-test passed after replacing the showNode push call"
        )


def main() -> None:
    check_landing_markup()
    check_graph_data()
    landing = (ROOT / "assets" / "page-graph.js").read_text(encoding="utf-8")
    full = (ROOT / "assets" / "graph.js").read_text(encoding="utf-8")
    css = (ROOT / "assets" / "pagecss" / "content.css").read_text(encoding="utf-8")
    check_source_contracts(landing, full)
    check_responsive_motion_contracts(css, landing)
    check_history_mutation_guard(landing, full)
    check_responsive_motion_mutation_guards(css, landing)
    print("graph explorer check passed: landing control, parity, click/history, responsive, and reduced-motion contracts")


if __name__ == "__main__":
    main()
