#!/usr/bin/env python3
"""Derive per-wiki-page publish/modified dates from git history.

Wiki front matter carries no dates, but Article structured data and sitemap
`<lastmod>` both want honest timestamps. Rather than make authors maintain a
field, we read them from git: the oldest commit touching a file is its publish
date, the newest its modified date. Output is `_data/wiki_dates.yml`, keyed by
slug, which the layout reads for JSON-LD and `scripts/prune_sitemap.py` reads
for `<lastmod>`.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "_wiki"
DATA_FILE = ROOT / "_data" / "wiki_dates.yml"


def _git_dates(path: Path) -> tuple[str, str] | None:
    """Return (published, modified) as YYYY-MM-DD, or None if untracked."""
    try:
        out = subprocess.run(
            ["git", "log", "--follow", "--format=%ad", "--date=short", "--", str(path)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    except subprocess.CalledProcessError:
        return None
    if not out:
        return None
    # git log is newest-first
    return out[-1], out[0]


def wiki_dates_map() -> dict[str, dict[str, str]]:
    dates: dict[str, dict[str, str]] = {}
    if not WIKI_DIR.exists():
        return dates
    for path in sorted(WIKI_DIR.glob("*.md")):
        if path.name == "README.md":
            continue
        result = _git_dates(path)
        if not result:
            continue
        published, modified = result
        dates[path.stem] = {"date": published, "last_modified_at": modified}
    return dates


def main() -> None:
    dates = wiki_dates_map()
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/stamp_wiki_dates.py from git history. Do not edit."]
    for slug, value in dates.items():
        lines.append(f"{slug}:")
        lines.append(f"  date: {value['date']}")
        lines.append(f"  last_modified_at: {value['last_modified_at']}")
    DATA_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"stamped {len(dates)} wiki dates -> {DATA_FILE}")


if __name__ == "__main__":
    main()
